#!/usr/bin/env bash
# Regenerate the app's backend config from the deployed CloudFormation stack.
#
# Run after any `cdk deploy` that changes an output. Values are public
# identifiers only — the API's address and the voice socket's — both of which
# ship inside the app binary anyway. Authentication is not here: Clerk owns it,
# and its publishable key lives in app.json where a build can always reach it.
set -euo pipefail

STACK="${STACK:-Mr20PendantStack}"
REGION="${REGION:-ap-south-1}"
TARGET="$(dirname "$0")/mobile/src/api/config.ts"

echo "reading outputs from $STACK in $REGION..."
outputs=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query 'Stacks[0].Outputs' --output json)

# Optional outputs return empty rather than failing: the voice service and the
# API's custom domain are each deployed independently of the app's config.
get() { echo "$outputs" | python3 -c "import json,sys;print(next((o['OutputValue'] for o in json.load(sys.stdin) if o['OutputKey']=='$1'), ''))"; }

api=$(get ApiCustomDomainUrl)
# Until api.lyzn.ai has DNS pointed at it, fall back to the Function URL. A
# shipped build holds whichever of the two was current when it was made.
[ -n "$api" ] || api=$(get ApiUrl)

cat > "$TARGET" <<CONFIG
/**
 * Backend configuration, generated by sync-config.sh from the deployed
 * CloudFormation outputs. Do not edit by hand.
 *
 * Authentication is not here: Clerk owns it, and its publishable key lives in
 * app.json where a build can always reach it.
 */
export const config = {
  apiUrl: '$(echo "$api" | sed 's:/*$::')',
  region: '$(get Region)',
  /** Voice-chat WebSocket (voicewire protocol); empty until deployed. */
  voiceUrl: '$(get VoiceUrl)',
} as const;
CONFIG

echo "wrote $TARGET"
grep -E "apiUrl|region|voiceUrl" "$TARGET"
