/**
 * Backend configuration, generated by scripts-sync-config.sh from the deployed
 * CloudFormation outputs. Do not edit by hand.
 *
 * Authentication is not here: Clerk owns it, and its publishable key lives in
 * app.json where a build can always reach it.
 */
export const config = {
  apiUrl: 'https://q5ohcn5mup3gnmfnvgsie7y2xa0jeijv.lambda-url.ap-south-1.on.aws',
  region: 'ap-south-1',
  /** Voice-chat WebSocket (voicewire protocol); empty until deployed. */
  voiceUrl: 'ws://Mr20Pe-Voice-ywyH3JiorRMG-753359449.ap-south-1.elb.amazonaws.com/v1/voice',
} as const;
