// Generate src/routes/apps/brands.ts from simple-icons.
//
// Generated rather than hand-copied so a path is never a typo, and so
// regenerating after an upgrade is one command. Only the brands the app can
// show are emitted — importing simple-icons at runtime would pull three
// thousand icons into a bundle that needs a dozen.
//
// Some brands are deliberately absent: Slack, LinkedIn and YouTrack were
// removed from simple-icons at their owners' request. Those fall back to the
// generated letter tile, in their own brand colour.
import * as si from 'simple-icons'
import { writeFileSync } from 'node:fs'

const WANT = [
  ['whatsapp', 'siWhatsapp'],
  ['google_workspace', 'siGoogle'],
  ['google', 'siGoogle'],
  ['github', 'siGithub'],
  ['notion', 'siNotion'],
  ['discord', 'siDiscord'],
  ['jira', 'siJira'],
  ['x', 'siX'],
  ['instagram', 'siInstagram'],
  ['claude_code', 'siClaude'],
  ['claude', 'siClaude'],
  ['gmail', 'siGmail'],
]

// Brands with no icon available, but a known colour worth keeping.
const COLOUR_ONLY = {
  slack: '4A154B',
  linkedin: '0A66C2',
  youtrack: '8A2BE2',
  keka: '00A99D',
  codex: '10A37F',
  gateway: '8B8CF5',
  push: '5EC98E',
  ntfy: '55AADD',
}

const rows = []
for (const [id, key] of WANT) {
  const icon = si[key]
  if (!icon) {
    console.warn(`skipping ${id}: ${key} is not in simple-icons`)
    continue
  }
  rows.push(
    `  ${JSON.stringify(id)}: { title: ${JSON.stringify(icon.title)}, hex: '#${icon.hex}', path: ${JSON.stringify(icon.path)} },`,
  )
}

const colours = Object.entries(COLOUR_ONLY)
  .map(([id, hex]) => `  ${JSON.stringify(id)}: '#${hex}',`)
  .join('\n')

const out = `// GENERATED by scripts/make-brands.mjs — do not edit.
//
// Marks from simple-icons (icons are CC0; the trademarks belong to their
// owners). Run \`npm run brands\` to regenerate.

export interface Brand {
  title: string
  /** The official brand colour. */
  hex: string
  /** A single SVG path, drawn in a 24x24 viewBox. */
  path: string
}

export const BRANDS: Record<string, Brand> = {
${rows.join('\n')}
}

/** Brands with no usable mark, but a colour worth keeping for the fallback
 *  tile. Slack, LinkedIn and YouTrack are here because their owners asked to
 *  be removed from the icon set. */
export const BRAND_COLOURS: Record<string, string> = {
${colours}
}
`

writeFileSync('src/routes/apps/brands.ts', out)
console.log(`wrote src/routes/apps/brands.ts — ${rows.length} marks, ${Object.keys(COLOUR_ONLY).length} colours`)
