// The QR code wacli draws in the terminal, drawn properly.
//
// The reading lives in ./qr, which is plain TypeScript so it can be tested
// against a code generated by the very library wacli prints with. This file is
// only the drawing.
import { toMatrix } from '@/routes/apps/qr'

export { findQrBlock } from '@/routes/apps/qr'

/** The code as crisp squares, at whatever size it is given. */
export function QrBlocks({ rows, size = 260 }: { rows: string[]; size?: number }) {
  const matrix = toMatrix(rows)
  const h = matrix.length
  const w = matrix[0]?.length ?? 0
  if (!h || !w) return null

  const cells: string[] = []
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (matrix[y][x]) cells.push(`M${x} ${y}h1v1h-1z`)
    }
  }

  return (
    <svg
      viewBox={`0 0 ${w} ${h}`}
      width={size}
      height={(size * h) / w}
      shapeRendering="crispEdges"
      role="img"
      aria-label="WhatsApp pairing QR code"
      // White ground in both themes, and a margin of its own: a phone reading
      // this needs the quiet zone to be light whatever the app is wearing.
      style={{ background: '#fff', padding: 10, boxSizing: 'content-box' }}
    >
      <path d={cells.join('')} fill="#000" />
    </svg>
  )
}
